part of 'home_bloc.dart';

class HomeState extends Equatable {
  final ScrollController popularScrollCtrl,
      globalScrollCtrl,
      followScrollCtrl,
      filterScrollCtrl,
      lastCreateScrollCtrl,
      friendsScrollCtrl,
      streamScrollCtrl;

  final int popularIndex,
      friendsIndex,
      globalIndex,
      followIndex,
      streamIndex,
      lastCreateIndex,
      myRoomTabControllerIndex;

  final int currentIndex,
      popularCurrentPage,
      filterCurrentPage,
      globalCurrentPage,
      followCurrentPage,
      friendsCurrentPage,
      liveCurrentPage,
      lastCreateCurrentPage,
      countryId,
      filterCountryId,
      popularLastPage,
      globalLastPage,
      streamLastPage,
      friendsLastPage,
      filterLastPage,
      followLastPage,
      lastCreateLastPage;

  final RequestState reqStateFriends,
      reqStatePopular,
      reqStateGlobal,
      reqStateLive,
      reqStateFilter,
      reqStateLastCreate,
      reqStateFollow,
      reqStateHostLevels,
      reqStatePickBox;

  final bool isPaginatingPopular,
      isPaginatingGlobal,
      isPaginatingFollow,
      isPaginatingFriends,
      isPaginatingFilter,
      isPaginatingLastCreate,
      isPaginatingLive;

  final List<RoomEntity> popular,
      popularPK,
      lastCreate,
      filteredRooms,
      global,
      follow,
      friends,
      stream;
  final String messagePopular,
      messageFilterMessage,
      messageGlobal,
      messageFollow,
      messageLastCreate,
      messageLive,
      messageFriends,
      pickBoxMsg;
  final HostLevelsEntity? hostLevelsEntity;

  const HomeState({
    this.currentIndex = 1,
    this.globalCurrentPage = 1,
    this.friendsCurrentPage = 1,
    this.popularCurrentPage = 1,
    this.filterCurrentPage = 1,
    this.lastCreateCurrentPage = 1,
    this.liveCurrentPage = 1,
    this.popularLastPage = -1,
    this.friendsLastPage = -1,
    this.filterLastPage = -1,
    this.globalLastPage = -1,
    this.lastCreateLastPage = -1,
    this.streamLastPage = -1,
    required this.popularScrollCtrl,
    required this.globalScrollCtrl,
    required this.friendsScrollCtrl,
    required this.lastCreateScrollCtrl,
    required this.streamScrollCtrl,
    this.followCurrentPage = 1,
    this.followLastPage = -1,
    required this.followScrollCtrl,
    required this.filterScrollCtrl,
    this.reqStatePopular = RequestState.idle,
    this.reqStateGlobal = RequestState.idle,
    this.reqStateFollow = RequestState.idle,
    this.reqStateFriends = RequestState.idle,
    this.reqStateFilter = RequestState.idle,
    this.reqStateLive = RequestState.idle,
    this.reqStateLastCreate = RequestState.idle,
    this.popular = const [],
    this.popularPK = const [],
    this.global = const [],
    this.follow = const [],
    this.friends = const [],
    this.stream = const [],
    this.filteredRooms = const [],
    this.lastCreate = const [],
    this.messagePopular = "",
    this.messageGlobal = "",
    this.messageFollow = "",
    this.messageFriends = "",
    this.messageLastCreate = "",
    this.messageLive = "",
    this.messageFilterMessage = "",
    this.popularIndex = 0,
    this.globalIndex = 0,
    this.followIndex = 0,
    this.friendsIndex = 0,
    this.lastCreateIndex = 0,
    this.countryId = 0,
    this.filterCountryId = 0,
    this.myRoomTabControllerIndex = 0,
    this.streamIndex = 0,
    this.reqStateHostLevels = RequestState.idle,
    this.hostLevelsEntity,
    this.reqStatePickBox = RequestState.idle,
    this.pickBoxMsg = '',
    this.isPaginatingPopular = false,
    this.isPaginatingGlobal = false,
    this.isPaginatingFollow = false,
    this.isPaginatingFriends = false,
    this.isPaginatingFilter = false,
    this.isPaginatingLastCreate = false,
    this.isPaginatingLive = false,
  });

  HomeState copyWith({
    int? currentIndex,
    List<RoomEntity>? popular,
    List<RoomEntity>? popularPK,
    List<RoomEntity>? global,
    List<RoomEntity>? follow,
    List<RoomEntity>? friends,
    List<RoomEntity>? filteredRooms,
    List<RoomEntity>? lastCreate,
    List<RoomEntity>? stream,
    String? messagePopular,
    String? messageGlobal,
    String? messageFollow,
    String? messageFriends,
    String? messageFilterMessage,
    String? messageLastCreate,
    String? messageLive,
    RequestState? reqStatePopular,
    RequestState? reqStateGlobal,
    RequestState? reqStateFollow,
    RequestState? reqStateFriends,
    RequestState? reqStateFilter,
    RequestState? reqStateLastCreate,
    RequestState? reqStateLive,
    int? popularCurrentPage,
    int? filterCurrentPage,
    int? globalCurrentPage,
    int? followCurrentPage,
    int? friendsCurrentPage,
    int? liveCurrentPage,
    int? lastCreateCurrentPage,
    int? globalLastPage,
    int? popularLastPage,
    int? followLastPage,
    int? friendsLastPage,
    int? streamLastPage,
    int? filterLastPage,
    int? lastCreateLastPage,
    ScrollController? globalScrollCtrl,
    ScrollController? popularScrollCtrl,
    ScrollController? followScrollCtrl,
    ScrollController? filterScrollCtrl,
    ScrollController? friendsScrollCtrl,
    ScrollController? lastCreateScrollCtrl,
    ScrollController? streamScrollCtrl,
    int? popularIndex,
    int? myRoomTabControllerIndex,
    int? globalIndex,
    int? friendsIndex,
    int? lastCreateIndex,
    int? streamIndex,
    int? countryId,
    int? filterCountryId,
    int? followIndex,
    RequestState? reqStateHostLevels,
    HostLevelsEntity? hostLevelsEntity,
    RequestState? reqStatePickBox,
    String? pickBoxMsg,
    bool? isPaginatingPopular,
    bool? isPaginatingGlobal,
    bool? isPaginatingFollow,
    bool? isPaginatingFriends,
    bool? isPaginatingFilter,
    bool? isPaginatingLastCreate,
    bool? isPaginatingLive,
  }) {
    return HomeState(
      currentIndex: currentIndex ?? this.currentIndex,
      reqStatePopular: reqStatePopular ?? this.reqStatePopular,
      reqStateLastCreate: reqStateLastCreate ?? this.reqStateLastCreate,
      reqStateGlobal: reqStateGlobal ?? this.reqStateGlobal,
      reqStateFollow: reqStateFollow ?? this.reqStateFollow,
      reqStateFriends: reqStateFriends ?? this.reqStateFriends,
      reqStateFilter: reqStateFilter ?? this.reqStateFilter,
      reqStateLive: reqStateLive ?? this.reqStateLive,
      popular: popular ?? this.popular,
      popularPK: popularPK ?? this.popularPK,
      global: global ?? this.global,
      follow: follow ?? this.follow,
      friends: friends ?? this.friends,
      lastCreate: lastCreate ?? this.lastCreate,
      stream: stream ?? this.stream,
      filteredRooms: filteredRooms ?? this.filteredRooms,
      messagePopular: messagePopular ?? this.messagePopular,
      messageGlobal: messageGlobal ?? this.messageGlobal,
      messageFollow: messageFollow ?? this.messageFollow,
      messageFriends: messageFriends ?? this.messageFriends,
      messageLastCreate: messageLastCreate ?? this.messageLastCreate,
      messageFilterMessage: messageFilterMessage ?? this.messageFilterMessage,
      messageLive: messageLive ?? this.messageLive,
      popularCurrentPage: popularCurrentPage ?? this.popularCurrentPage,
      filterCurrentPage: filterCurrentPage ?? this.filterCurrentPage,
      globalCurrentPage: globalCurrentPage ?? this.globalCurrentPage,
      followCurrentPage: followCurrentPage ?? this.followCurrentPage,
      friendsCurrentPage: friendsCurrentPage ?? this.friendsCurrentPage,
      lastCreateCurrentPage:
          lastCreateCurrentPage ?? this.lastCreateCurrentPage,
      followScrollCtrl: followScrollCtrl ?? this.followScrollCtrl,
      filterScrollCtrl: filterScrollCtrl ?? this.filterScrollCtrl,
      popularScrollCtrl: popularScrollCtrl ?? this.popularScrollCtrl,
      globalScrollCtrl: globalScrollCtrl ?? this.globalScrollCtrl,
      friendsScrollCtrl: friendsScrollCtrl ?? this.friendsScrollCtrl,
      lastCreateScrollCtrl: lastCreateScrollCtrl ?? this.lastCreateScrollCtrl,
      streamScrollCtrl: streamScrollCtrl ?? this.streamScrollCtrl,
      followLastPage: followLastPage ?? this.followLastPage,
      friendsLastPage: friendsLastPage ?? this.friendsLastPage,
      filterLastPage: filterLastPage ?? this.filterLastPage,
      popularLastPage: popularLastPage ?? this.popularLastPage,
      globalLastPage: globalLastPage ?? this.globalLastPage,
      lastCreateLastPage: lastCreateLastPage ?? this.lastCreateLastPage,
      popularIndex: popularIndex ?? this.popularIndex,
      globalIndex: globalIndex ?? this.globalIndex,
      followIndex: followIndex ?? this.followIndex,
      friendsIndex: friendsIndex ?? this.friendsIndex,
      lastCreateIndex: lastCreateIndex ?? this.lastCreateIndex,
      countryId: countryId ?? this.countryId,
      filterCountryId: filterCountryId ?? this.filterCountryId,
      myRoomTabControllerIndex:
          myRoomTabControllerIndex ?? this.myRoomTabControllerIndex,
      liveCurrentPage: liveCurrentPage ?? this.liveCurrentPage,
      streamLastPage: streamLastPage ?? this.streamLastPage,
      streamIndex: streamIndex ?? this.streamIndex,
      reqStateHostLevels: reqStateHostLevels ?? this.reqStateHostLevels,
      hostLevelsEntity: hostLevelsEntity ?? this.hostLevelsEntity,
      reqStatePickBox: reqStatePickBox ?? this.reqStatePickBox,
      pickBoxMsg: pickBoxMsg ?? this.pickBoxMsg,
      isPaginatingPopular: isPaginatingPopular ?? this.isPaginatingPopular,
      isPaginatingGlobal: isPaginatingGlobal ?? this.isPaginatingGlobal,
      isPaginatingFollow: isPaginatingFollow ?? this.isPaginatingFollow,
      isPaginatingFriends: isPaginatingFriends ?? this.isPaginatingFriends,
      isPaginatingFilter: isPaginatingFilter ?? this.isPaginatingFilter,
      isPaginatingLastCreate:
          isPaginatingLastCreate ?? this.isPaginatingLastCreate,
      isPaginatingLive: isPaginatingLive ?? this.isPaginatingLive,
    );
  }

  @override
  List<Object?> get props => [
        currentIndex,
        reqStatePopular,
        reqStateGlobal,
        reqStateFriends,
        reqStateLastCreate,
        reqStateLive,
        reqStateFilter,
        reqStateFollow,
        reqStateHostLevels,
        reqStatePickBox,
        popular,
        popularPK,
        global,
        follow,
        friends,
        stream,
        lastCreate,
        filteredRooms,
        messagePopular,
        messageGlobal,
        messageFollow,
        messageFriends,
        messageLastCreate,
        messageFilterMessage,
        messageLive,
        pickBoxMsg,
        popularCurrentPage,
        liveCurrentPage,
        filterCurrentPage,
        lastCreateCurrentPage,
        globalCurrentPage,
        friendsCurrentPage,
        followCurrentPage,
        popularLastPage,
        globalLastPage,
        streamLastPage,
        friendsLastPage,
        filterLastPage,
        followLastPage,
        lastCreateLastPage,
        popularIndex,
        followIndex,
        streamIndex,
        friendsIndex,
        globalIndex,
        lastCreateIndex,
        countryId,
        filterCountryId,
        myRoomTabControllerIndex,
        hostLevelsEntity,
        isPaginatingPopular,
        isPaginatingGlobal,
        isPaginatingFollow,
        isPaginatingFriends,
        isPaginatingFilter,
        isPaginatingLastCreate,
        isPaginatingLive,
      ];
}
