<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use Google\Cloud\Storage\StorageClient;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class StorageUploadController extends Controller
{
    public function chatVideo(Request $request){
         // Validate the request
         $request->validate([
            'name' => 'required|string',
            'type' => 'required|string',
            'folder' => 'nullable|string'
        ]);

        $filename = $request->input('name');
        $filetype = $request->input('type');
        $folder = $request->folder ?? 'pre-sign';

        // Generate a unique file name to avoid conflicts
        $uniqueFilename = $folder . '/' . Str::uuid() . '_' . $filename;

        // Dual-driver: on S3 deploys the pre-signed PUT/DELETE are generated by
        // the S3 adapter; the GCS path below is untouched (default deploy).
        if ($this->mediaDriver() === 's3') {
            $disk = Storage::disk('gcs'); // 'gcs'-named disk, driver=s3 here

            $upload = $disk->temporaryUploadUrl(
                $uniqueFilename,
                now()->addMinutes(15),
                ['ContentType' => $filetype]
            );

            // Presign the DELETE on the same underlying S3 client so the app
            // keeps its two-URL contract (upload_url + delete_url).
            $client = $disk->getClient();
            $bucket = config('filesystems.disks.gcs.bucket');
            $deleteRequest = $client->createPresignedRequest(
                $client->getCommand('DeleteObject', [
                    'Bucket' => $bucket,
                    'Key'    => $uniqueFilename,
                ]),
                now()->addMinutes(30)
            );

            return response()->json([
                'upload_url' => $upload['url'],
                'delete_url' => (string) $deleteRequest->getUri(),
                'name'       => $uniqueFilename,
            ]);
        }

        // Pre-signed URL targets the SAME panel-managed GCS bucket the app reads
        // media from (utd-test-storage), not the legacy app.google_cloud_* env
        // (a legacy base-image leftover), which sent uploads to the wrong
        // bucket so the media 404'd on the app's storage_url.
        $bucket = \App\Helpers\GcsHelper::bucket();

        // Generate a pre-signed URL with optional metadata
        $object = $bucket->object($uniqueFilename);

        $url = $object->signedUrl(
            now()->addMinutes(15),
            [
                'method' => 'PUT',
                'contentType' => $filetype
            ]
        );

        $deleteUrl = $object->signedUrl(now()->addMinutes(30), [
            'method' => 'DELETE',
        ]);

        return response()->json([
            'upload_url' => $url,
            'delete_url' => $deleteUrl,
            'name' => $uniqueFilename,
        ]);
    }

    /**
     * Effective media storage driver of the 'gcs'-named disk: 'gcs' (default) or
     * 's3'. Reads the resolved disk config so it honours MEDIA_STORAGE_DRIVER
     * even after config:cache.
     */
    private function mediaDriver(): string
    {
        return (string) config('filesystems.disks.gcs.driver', 'gcs');
    }
}
