<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use Google\Cloud\Storage\StorageClient;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class UploadLinkController extends Controller
{
    public function uploadLink(Request $request)
    {
        // Validate the request
        $request->validate([
            'name' => 'required|string',
            'type' => 'required|string',
            'size' => 'nullable|integer',
            'folder' => 'nullable|string'
        ]);

        $filename = $request->input('name');
        $filetype = $request->input('type');
        $size = $request->input('size'); // Optional
        $folder = 'pre-sign';

        if(!empty($request->folder)){
            $folder = $request->folder;
        }
        // Generate a unique file name to avoid conflicts
        $uniqueFilename = $folder . '/' . Str::uuid() . '_' . $filename;

        // Dual-driver: on S3 deploys the pre-signed PUT URL is generated by the
        // S3 adapter; the GCS path below is untouched (default deploy).
        if ((string) config('filesystems.disks.gcs.driver', 'gcs') === 's3') {
            $upload = Storage::disk('gcs')->temporaryUploadUrl(
                $uniqueFilename,
                now()->addMinutes(15),
                ['ContentType' => $filetype]
            );

            return response()->json([
                'upload_url' => $upload['url'],
                'name'       => $uniqueFilename,
            ]);
        }

        // Pre-signed URL targets the SAME panel-managed GCS bucket the app reads
        // media from (utd-test-storage), not the legacy app.google_cloud_* env
        // (a legacy base-image leftover), which sent uploads to the wrong
        // bucket so the media 404'd on the app's storage_url.
        $bucket = \App\Helpers\GcsHelper::bucket();

        // Generate a pre-signed URL
        $object = $bucket->object($uniqueFilename);

        $url = $object->signedUrl(
            now()->addMinutes(15), // URL expiration time (e.g., 15 minutes)
            [
                'method' => 'PUT', // HTTP method for upload
                'contentType' => $filetype, // Set the file type
            ]
        );

        return response()->json([
            'upload_url' => $url,
            'name' => $uniqueFilename,
        ]);
    }
}
