org.gradle.jvmargs=-Xmx5g -XX:MaxMetaspaceSize=2g -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.compiler.execution.strategy=in-process -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8
kotlin.compiler.execution.strategy=in-process
android.enableJetifier=true
android.enableR8=true
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
