[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
process_name=%(program_name)s
command=php /app/artisan schedule:work
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/scheduler.log

[program:critical-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=default,notification,notification_heavy,wallet,increment-diamond,roomBoomRewards --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/critical-worker.log

[program:heavy-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=heavy1,heavy2,heavy3,pk-job,updatePk,updatePkAndSendToZigo,achievement,level_rewards --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/heavy-worker.log

[program:background-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=luckyBox,lucky_gift,lucky_gift_2,lucky_gift_3,luckyGift,sendComment,log_user_coin,test-super-lucky-box,official-message,follow_counts,milestones-job --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/background-worker.log

[program:gifts-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work redis --queue=gifts --timeout=300 --tries=3 --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/gifts.log

[program:media-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=optimization-images --max-jobs=1000 --rest=1
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/media-worker.log

[program:stream-handling]
process_name=%(program_name)s
command=php /app/artisan app:handling-room-stream-requests
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/stream.log
