<?php

namespace App\Admin\Controllers;

use App\Models\Admin;
use App\Models\Agency;
use App\Models\Agent;
use App\Models\User;
use Encore\Admin\Auth\Permission;
use Encore\Admin\Form;
use Encore\Admin\Layout\Content;
use Illuminate\Support\Facades\DB;
use Modules\RoleRewards\Actions\DeleteUser;
use Modules\RoleRewards\Helpers\UserRewardHelper;
use Modules\RoleRewards\Helpers\UserRoleRewardHelper;

class AdminUserController extends EncorUsersController
{
// \Encore\Admin\Controllers\UserController

    protected $model;

    public $permission_name = 'auth-users';

    public function __construct ()
    {
        $userModel = Admin::class;
        $this->model = new $userModel;
    }

    public function edit ( $id , Content $content )
    {
       // Permission::check('developer');

        return parent ::edit ( $id , $content ); // TODO: Change the autogenerated stub
    }

    public function grid ()
    {

        $grid =  parent::grid();

        $grid->actions(function ( $actions) {
                $actions->disableDelete();
                $actions->add(new DeleteUser());
        });

        return $grid;

    }

    public function update ( $id )
    {
        $user = Admin::query ()->findOrFail ($id);
        if (\request ('password') != $user->password || \request ('username') != $user->username){
            Agent::where("id",$user->id)->update([
                "remember_token" => null
            ]);
            DB::table ('sessions')->where ('user_id',$user->id)->delete ();
        }
        return parent ::update ($id);
    }

    public function destroy ( $id )
    {

        $user = $this->model->find($id);
        if ($user){
            if ($user->isRole('admin') || $user->isRole('developer')){
                return response ()->json (['error'=>'','message'=>__('admin cant be deleted')]);
            }
        }
        Agency::query ()->where ('owner_id',$id)->delete ();


        return parent ::destroy ($id);

    }

    public function form ()
    {

        $form =  parent ::form ();
        $form->select('app_id', __('validation.select_user'))->options(function ($value) {
            if (!$value) return [];
            $user = User::find($value);
            return $user ? [$user->id => $user->uuid . '_' . $user->name] : [];
        })->ajax('/api/search/users3', 'id', 'name')
            ->help(__('اختياري — لربط الموظف بحساب مستخدم في التطبيق (لنظام مكافآت الأدوار مستقبلًا). اتركه فارغًا لإضافة موظف عادي.'));


        $form->saving(function (Form $form) {
            $model = $form->model();

            $oldAppId  = $model->getOriginal('app_id');
            $newAppId  = $form->app_id;

            $oldRoles = $model->exists
                ? $model->roles()->get(['id', 'slug'])->map(fn($r) => ['id' => (int)$r->id, 'slug' => $r->slug])->toArray()
                : [];

            $newRoles = collect($form->roles ?? [])
                ->filter()
                ->map(function ($id) {
                    $role = \Encore\Admin\Auth\Database\Role::find($id);
                    return $role ? ['id' => (int)$role->id, 'slug' => $role->slug] : null;
                })
                ->filter()
                ->toArray();

            if ($model->exists) {

                if ($oldAppId && $oldAppId != $newAppId) {
                    $oldUser = User::find($oldAppId);
                    if ($oldUser) {
                        foreach ($oldRoles as $role) {
                            UserRoleRewardHelper::revokeRoleRewards($oldUser, $role['id'], $role['slug']);
                        }
                    }
                }

                $rolesRemoved = array_udiff($oldRoles, $newRoles, fn($a, $b) => $a['id'] <=> $b['id']);
                $rolesAdded   = array_udiff($newRoles, $oldRoles, fn($a, $b) => $a['id'] <=> $b['id']);

                $user = User::find($newAppId);
                if ($user) {
                    foreach ($rolesRemoved as $role) {
                        UserRoleRewardHelper::revokeRoleRewards($user, $role['id'], $role['slug']);
                    }

                    foreach ($rolesAdded as $role) {
                        UserRoleRewardHelper::giveRoleRewards($user, $role['id'], $role['slug']);
                    }
                }
            }
        });

        $form->saved(function (Form $form) {
            $model = $form->model();
            $user  = User::find($model->app_id);

            $newRoles = $model->roles()->get(['id', 'slug'])->map(fn($r) => ['id' => (int)$r->id, 'slug' => $r->slug]);

            if ($user) {
                foreach ($newRoles as $role) {
                    UserRoleRewardHelper::giveRoleRewards($user, $role['id'], $role['slug']);
                }
            }
        });

        $form->deleted(function (Form $form) {
            $model = $form->model();
            $user  = User::find($model->app_id);

            if ($user) {
                foreach ($model->roles as $role) {
                    UserRoleRewardHelper::revokeRoleRewards($user, (int)$role->id, $role->slug);
                }
            }
        });
        return $form;
    }


}
