<?php

namespace App\Admin\Controllers;

use Admin as GlobalAdmin;
use App\Models\Admin as ModelsAdmin;
use App\Models\Agent;
use Encore\Admin\Form;
use Illuminate\Http\Request;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Layout\Content;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\MessageBag;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Cookie;
use KevinSoft\MultiLanguage\MultiLanguage;
use Encore\Admin\Controllers\AuthController as BaseAuthController;

class AuthController extends BaseAuthController
{

    public function createPreviewUser(Request $request)
    {
        if (!Admin::user()->can('*')) {
            abort(403);
        }

        \App\Models\Admin::where('is_preview', true)->delete();

        $roleId = $request->role_id;
        if (!\App\Models\Role::whereKey($roleId)->exists()) {
            abort(422);
        }
        $password = \Str::random(12);
        $values = [
            'username' => \Str::random(9),
            'password' => $password,
        ];
        $admin = \App\Models\Admin::create([
            ...$values,
            'name' => \Str::random(9),
            'is_preview' => true,
            'password' => bcrypt($password)
        ]);

        $admin->roles()->sync(['role_id' => $roleId]);
        \App\Models\Admin::forgetCachedPermissionsFor($admin->id);
        //        Config::set('session.cookie', 'laravel_preview');
        //        Config::set('session.domain', 'https://top_star_backend.test');

        $token = '';



        return response()->json(['url' => '/preview/admin/login?token=' . $admin->id]);
    }

    public function putSetting()
    {
        if (\request('password') != Admin::user()->getAuthPassword()) {
            Agent::where("id", Admin::user()->id)->update([
                "remember_token" => null
            ]);
            DB::table('sessions')->where('user_id', Admin::user()->getAuthIdentifier())->delete();
        }
        return parent::putSetting(); // TODO: Change the autogenerated stub
    }

    public function getLogin()
    {
        $languages = MultiLanguage::config("languages");
        $cookie_name = MultiLanguage::config('cookie-name', 'locale');

        $current = MultiLanguage::config('default');
        if (Cookie::has($cookie_name)) {
            $current = Cookie::get($cookie_name);
        }
        return view("multi-language::login", compact('languages', 'current'));
    }

    // public function postLogin(Request $request)
    // {

    //     $url = $request->url;

    //     $this->loginValidator($request->all())->validate();
    //     $admin = DB::table('admin_users')
    //         ->where('username', request('username'))
    //         ->where('type', null)
    //         ->exists();
    //     if ($admin) {
    //         $credentials = $request->only([$this->username(), 'password']);
    //         $remember = $request->get('remember', false);

    //         if ($this->guard()->attempt($credentials, $remember)) {
    //             return $this->sendLoginResponse($request);
    //         }
    //     }


    //     return back()->withInput()->withErrors([
    //         $this->username() => $this->getFailedLoginMessage(),
    //     ]);
    // }

    // public function sendLoginResponse(Request $request)
    // {
    //     admin_toastr(trans('admin.login_successful'));

    //     $request->session()->regenerate();
    //     if (Auth::user()->roles->contains('slug', 'bd')) {
    //         return redirect()->route('bd.home');
    //     }
    //    // dd(Auth::user());

    //     return redirect()->intended($request->url ?? $this->redirectPath());
    // }



    public function postLogin(Request $request)
    {
        $this->loginValidator($request->all())->validate();

        // Panel staff are identified by type='employee'. Profit-position
        // accounts (country/region/bd/...) sign in through their own gates.
        $admin = DB::table('admin_users')
            ->where('username', $request->username)
            ->where('type', 'employee')
            ->first();

        // Check if admin exists
        if (!$admin) {
            return back()->withInput()->withErrors([
                $this->username() => trans('admin.username_not_found'),
            ]);
        }

        // Check password manually (if using bcrypt)
        if (!Hash::check($request->password, $admin->password)) {
            return back()->withInput()->withErrors([
                'password' => trans('admin.password_incorrect'),
            ]);
        }

        // Login using the ID
        Auth::guard('admin')->loginUsingId($admin->id, $request->boolean('remember'));

        // Redirect
        return $this->sendLoginResponse($request);
    }

    public function sendLoginResponse(Request $request)
    {
        admin_toastr(trans('admin.login_successful'));

        $request->session()->regenerate();

        $user = Auth::guard('admin')->user();

        // Role-based redirect
        if ($user->roles->contains('slug', 'bd')) {
            return redirect()->route('bd.home');
        }

        $url = $this->getFirstUrl($user);

        // Honor the hidden `url` deep-link only when it points inside the admin
        // panel. Empty, "/admin", or any off-site value falls back to the user's
        // first permitted page — this stops the login from dumping the user on
        // the public marketing site and closes an open-redirect via `url`.
        $requested = (string) $request->input('url');
        $redirectUrl = ($requested !== '' && $requested !== '/admin' && str_starts_with($requested, '/admin/'))
            ? $requested
            : $url;

        return redirect()->intended($redirectUrl);
    }



    public function getFirstUrl($user)
    {
        $permissionSlugs = $user->roles
            ->flatMap->permissions
            ->unique('id')
            ->pluck('slug');

        if ($permissionSlugs->isEmpty()) {
            return admin_url(); // fallback
        }

        $firstPermission = DB::table('admin_permissions')
            ->join('role_categories', 'admin_permissions.category', '=', 'role_categories.slug')
            ->whereIn('admin_permissions.slug', $permissionSlugs)
            ->where('admin_permissions.slug', 'like', 'browse-%')
            ->orderBy('role_categories.sort', 'asc')
            ->orderBy('admin_permissions.id', 'asc')
            ->select('admin_permissions.slug')
            ->first();


        // Fallback if no permission found
        $permissionSlug = $firstPermission->slug ?? 'browse-dashboard';

        $menuUrl = DB::table('admin_menu')
            ->where('permission', $permissionSlug)
            ->whereNotNull('uri')
            ->where('uri', '!=', '')
            ->value('uri');

        return $menuUrl ? admin_url($menuUrl) : admin_url();
    }

    public function getSetting(Content $content)
    {
        $form = $this->settingForm();
        $form->tools(
            function (Form\Tools $tools) {
                $tools->disableList();
                $tools->disableDelete();
                $tools->disableView();
            }
        );

        return $content
            ->title(trans('admin.user_setting'))
            ->body($form->edit(Admin::user()->id));
    }

    protected function settingForm()
    {

        $class = config('admin.database.users_model');

        $form = new Form(new $class());

        $form->display('username', trans('admin.username'));
        $form->text('name', trans('admin.name'))->rules('required');
        $form->image('avatar', trans('admin.avatar'));
        if (!(Auth::user()->username == 'demo')) {
            $form->password('password', trans('admin.password'))->rules('confirmed|required');
            $form->password('password_confirmation', trans('admin.password_confirmation'))->rules('required')
                ->default(function ($form) {
                    return $form->model()->password;
                });
        }

        $form->setAction(admin_url('auth/setting'));

        $form->ignore(['password_confirmation']);

        $form->saving(function (Form $form) {
            if ($form->model()->password != $form->password && $form->model()->username == 'admin' || $form->model()->password_confirmation != $form->password_confirmation && $form->model()->username == 'admin') {
                $error = new MessageBag(
                    [
                        'title'   => 'forbidden',
                        'message' => 'you can not make change',
                    ]
                );
                return back()->with(compact('error'));
            }
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = Hash::make($form->password);
            }
        });

        $form->saved(function () {
            admin_toastr(trans('admin.update_succeeded'));

            return redirect(admin_url('auth/setting'));
        });

        return $form;
    }


    public function customLogout(Request $request)
    {
        Auth::guard('admin')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect('/areaManager/login');
    }

    public function customBdLogout(Request $request)
    {
        Auth::guard('admin')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect('/bd/login');
    }
    public function customSuperadminLogout(Request $request)
    {
        Auth::guard('admin')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect('/superadmin/login');
    }
}
