<?php

namespace App\Admin\Controllers;

use App\Helpers\Common;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Show;
use App\Enums\PermissionType;
use Encore\Admin\Facades\Admin;
use Illuminate\Validation\Rule;
use Encore\Admin\Layout\Content;
use Encore\Admin\Auth\Permission;
use Encore\Admin\Actions\Response;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Cache;
use Encore\Admin\Controllers\AdminController;

class EncorUsersController extends AdminController
{

    public $permission_name;
    public $hiddenColumns;

    protected $response;
    public function response()
    {
        if (is_null($this->response)) {
            $this->response = new Response();
        }

        if (method_exists($this, 'dialog')) {
            $this->response->swal();
        } else {
            $this->response->toastr();
        }

        return $this->response;
    }

    public function index(Content $content)
    {
        if (!Admin::user()->can('*')) {
            Permission::check('browse-' . $this->permission_name);
        }
        return parent::index($content); // TODO: Change the autogenerated stub
    }

    public function create(Content $content)
    {
        if (!Admin::user()->can('*')) {
            Permission::check('create-' . $this->permission_name);
        }

        return parent::create($content); // TODO: Change the autogenerated stub
    }

    public function store()
    {
        if (!Admin::user()->can('*')) {
            abort(403);
        }

        return $this->form()->store();
    }

    public function update($id)
    {
        if (!Admin::user()->can('*')) {
            Permission::check('update-' . $this->permission_name);
        }

        return parent::update($id); // TODO: Change the autogenerated stub
    }

    public function show($id, Content $content)
    {
        if (!Admin::user()->can('*')) {
            Permission::check('browse-' . $this->permission_name);
        }

        return parent::show($id, $content); // TODO: Change the autogenerated stub
    }

    public function edit($id, Content $content)
    {
        if (!Admin::user()->can('*')) {
            Permission::check('edit-' . $this->permission_name);
        }

        return parent::edit($id, $content); // TODO: Change the autogenerated stub
    }

    public function destroy($id)
    {
        if (!Admin::user()->can('*')) {
            Permission::check('delete-' . $this->permission_name);
        }

        return parent::destroy($id);
    }

    public function extendGrid($grid)
    {
        $permission_name = $this->permission_name;

        if (!Admin::user()->can('*')) {
            if (! Admin::user()->can('edit-' . $permission_name)) {
                $grid->hiddenColumns = $this->hiddenColumns;
            }
            if (! Admin::user()->can('delete-' . $permission_name)) {
                $grid->disableRowSelector();
            }
            if (! Admin::user()->can('create-' . $permission_name)) {
                $grid->disableCreateButton();
            }
            $grid->actions(
                function ($actions) use ($permission_name) {

                    // The roles with this permission will not able to see the delete button in actions column.
                    if (! Admin::user()->can('delete-' . $permission_name)) {
                        $actions->disableDelete();
                    }
                    if (! Admin::user()->can('edit-' . $permission_name)) {
                        $actions->disableEdit();
                    }
                    if (! Admin::user()->can('browse-' . $permission_name)) {
                        $actions->disableView();
                    }
                }
            );
            if (! Admin::user()->can('edit-' . $permission_name) && ! Admin::user()->can('delete-' . $permission_name) && ! Admin::user()->can('create-' . $permission_name)) {
                $grid->disableActions();
            }
        }



        $grid->export(function ($export) use ($grid) {

            $export->filename($this->permission_name . '.csv');
            if ($this->hiddenColumns == null) {
                $export->except([]);
            } else {
                $export->except($this->hiddenColumns);
            }

            //            $export->only(['column3', 'column4' ...]);
            //
            $export->originalValue($grid->columnNames);
            //
            //            $export->column('column_5', function ($value, $original) {
            //                return $value;
            //            });
        });
    }


    public function extendShow($show)
    {
        if (!Admin::user()->can('*')) {
            $show->panel()
                ->tools(
                    function ($tools) {
                        $tools->disableEdit();
                        $tools->disableList();
                        $tools->disableDelete();
                    }
                );
        }
    }

    protected function title()
    {
        return trans('admin.administrator');
    }

    protected function grid()
    {
        $permission_name = $this->permission_name;

        //        $userModel = config('admin.database.users_model');
        // Identity resolved centrally: super-admin preview honoured, real
        // managers pinned to their own id (no raw request/session override).
        $roleAuthId = Common::resolveAreaManagerId();

        $grid = new Grid(new \App\Models\Admin());
     //   $countryID = empty((array)session('filter_country_id'));

        $grid->model()->with(['agency', 'roles', 'createdBy'])
            ->when(empty($roleAuthId), fn($q) => $q->where('type', 'employee'))
            ->where('is_preview', 0)
            ->whereDoesntHave('roles', function ($query) {
                $query->where('slug', 'agency-owner');
            });
        if ($roleAuthId) {
            $grid->model()->where('parent_id', $roleAuthId);
        }
        $grid->column('id', 'ID')->sortable();
        $grid->column('username', trans('admin.username'));
        $grid->column('name', trans('admin.name'));
        $grid->column('roles', trans('admin.roles'))->pluck('name')->label();

        $grid->column('createdBy.name', __('created by'))->display(function () {
            $user = $this->createdBy;
            $name = $user->name ?? '';

            if (request()->filled('_export_')) {
                return $name;
            }
            if (!$user) return "<span style='color: red;'>غير مرتبط</span>";

            $id = $user->id ?? 'غير معروف';
            $path = $user->avatar ?? null;
            $defaultImage = asset("images/businessman-icon.jpg");
            $url = getImagePath($path) ?? $defaultImage;

            if (!isImageExists($url)) {
                $url = $defaultImage;
            }

            $image = handleShowImageWithTypes($this->id, $url, 40, 40);
            $showUrl = url("admin/users/{$user->id}");

            return "
                <div style='display: flex; align-items: center; gap: 10px;'>
                    $image
                    <div>
                       <a href='{$showUrl}' style='text-decoration: none; color: inherit; display: flex; align-items: center; gap: 10px;'>
                         <span style='text-decoration: underline; cursor: pointer;'>$name</span>
                        </a>
                        <span style='font-size: smaller;'>ID: $id</span>
                    </div>
                </div>
            ";
        });

        $grid->column('created_at', trans('admin.created_at'));
        $grid->column('updated_at', trans('admin.updated_at'));

        $grid->actions(function (Grid\Displayers\Actions $actions) use ($permission_name) {

            if (Admin::user()->can('*')) {
                return;
            }

            if (! Admin::user()->can('show-' . $permission_name)) {
                $actions->disableView();
            }
            if (! Admin::user()->can('edit-' . $permission_name)) {
                $actions->disableEdit();
            }
            if (! Admin::user()->can('delete-' . $permission_name)) {
                $actions->disableDelete();
            }

            if ($actions->getKey() == 1) {
                $actions->disableDelete();
            }
        });

        if (
            ! Admin::user()->can('show-' . $permission_name) &&
            ! Admin::user()->can('edit-'   . $permission_name) &&
            ! Admin::user()->can('delete-' . $permission_name)
        ) {
            $grid->disableActions();
        }

        $grid->tools(function (Grid\Tools $tools) {
            $tools->batch(function (Grid\Tools\BatchActions $actions) {
                $actions->disableDelete();
            });
        });

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     *
     * @return Show
     */
    protected function detail($id)
    {
        $userModel = config('admin.database.users_model');

        $show = new Show($userModel::findOrFail($id));

        $show->panel()
            ->tools(function ($tools) {
                $tools->disableEdit();
                $tools->disableDelete();
            });

        $show->field('id', 'ID');
        $show->field('username', trans('admin.username'));
        $show->field('name', trans('admin.name'));
        $show->field('roles', trans('admin.roles'))->as(function ($roles) {
            return $roles->pluck('name');
        })->label();
        $show->field('permissions', trans('admin.permissions'))->as(function ($permission) {
            return $permission->pluck('name');
        })->label();
        $show->field('created_at', trans('admin.created_at'));
        $show->field('updated_at', trans('admin.updated_at'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    public function form()
    {
        $userModel = config('admin.database.users_model');
        $permissionModel = config('admin.database.permissions_model');
        $roleModel = config('admin.database.roles_model');

        $form = new Form(new $userModel());
        if (request()->is('*edit*')) {
            $form->tools(function (Form\Tools $tools) {
                $tools->disableDelete();
            });
        }

        $form->hidden('created_by')->default(auth()->id());

        $userTable = config('admin.database.users_table');
        $connection = config('admin.database.connection');

        $form->display('id', 'ID');

        $form->text('username', trans('admin.username'))
            ->rules(function ($form) use ($connection, $userTable) {
                $table = "{$connection}.{$userTable}";

                $rules = ['required'];

                $uniqueRule = Rule::unique($table, 'username');

                if (! $form->isCreating()) {
                    $id = $form->model()?->id ?? null;
                    $uniqueRule->ignore($id);
                }

                $rules[] = $uniqueRule;

                return $rules;
            });

        $form->text('name', trans('admin.name'))->rules('required');
        $form->image('avatar', trans('admin.avatar'));
        $form->password('password', trans('admin.password'))->rules('required|confirmed');
        $form->password('password_confirmation', trans('admin.password_confirmation'))->rules('required')
            ->default(function ($form) {
                return $form->model()->password;
            });

        $form->ignore(['password_confirmation']);

        $form->multipleSelect('roles', trans('admin.roles'))->options($roleModel::where('type', 'admin')->get()->pluck('name', 'id'));
        // $form->multipleSelect('permissions', trans('admin.permissions'))->options($permissionModel::all()->pluck('name', 'id'));

        $form->display('created_at', trans('admin.created_at'));
        $form->display('updated_at', trans('admin.updated_at'));
        // Panel staff carry type='employee' so they can sign in through /admin.
        $form->hidden('type')->default('employee');
        $form->saving(function (Form $form) {
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = Hash::make($form->password);
            }
        });

        $form->saved(function (Form $form) {
            // Clear permissions cache for this user (important for Octane)
            if ($form->model()->id) {
                Cache::forget('admin_user_permissions_' . $form->model()->id);
            }
        });

        return $form;
    }
}
