<?php

namespace App\Admin\Controllers;

use Encore\Admin\Actions\Response;
use Encore\Admin\Auth\Permission;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Layout\Content;
use Encore\Admin\Form;

class MainController extends AdminController
{
    public $permission_name;

    public $hiddenColumns;

    protected $response;

    public function response()
    {
        if (is_null($this->response)) {
            $this->response = new Response();
        }

        if (method_exists($this, 'dialog')) {
            $this->response->swal();
        } else {
            $this->response->toastr();
        }

        return $this->response;
    }

    /**
     * Controllers that override an action and call parent:: with prepared
     * content must keep their exact behavior, so defaults are only built
     * when the action is NOT overridden by the child class.
     */
    protected function actionOverridden(string $method): bool
    {
        return (new \ReflectionMethod($this, $method))->getDeclaringClass()->getName() !== self::class;
    }

    public function index(Content $content)
    {
        try {
            Permission::check('browse-' . $this->permission_name);
        } catch (\Exception $e) {
            \Log::warning('Permission denied for user ' . auth()->id() . ' on ' . $this->permission_name);
            abort(403, 'Unauthorized access');
        }

        if ($this->actionOverridden('index') || !method_exists($this, 'grid')) {
            return $content;
        }

        return $content
            ->title($this->title())
            ->description($this->description['index'] ?? trans('admin.list'))
            ->body($this->grid());
    }

    public function create(Content $content)
    {
        Permission::check('create-' . $this->permission_name);

        if ($this->actionOverridden('create') || !method_exists($this, 'form')) {
            return $content;
        }

        return $content
            ->title($this->title())
            ->description($this->description['create'] ?? trans('admin.create'))
            ->body($this->form());
    }

    public function update($id)
    {
        Permission::check('edit-' . $this->permission_name);


        return parent::update($id); // TODO: Change the autogenerated stub
    }

    public function show($id, Content $content)
    {
        Permission::check('show-' . $this->permission_name);

        if ($this->actionOverridden('show') || !method_exists($this, 'detail')) {
            return $content;
        }

        return $content
            ->title($this->title())
            ->description($this->description['show'] ?? trans('admin.show'))
            ->body($this->detail($id));
    }

    public function edit($id, Content $content)
    {
        Permission::check('edit-' . $this->permission_name);

        if ($this->actionOverridden('edit') || !method_exists($this, 'form')) {
            return $content;
        }

        return $content
            ->title($this->title())
            ->description($this->description['edit'] ?? trans('admin.edit'))
            ->body($this->form()->edit($id));
    }

    public function destroy($id)
    {
        Permission::check('delete-' . $this->permission_name);


        return parent::destroy($id);
    }

    public function extendGrid($grid)
    {
        if(!request()->is('admin/rooms') && !request()->is('admin/emojis') && !request()->is('admin/countries') &&
        !request()->is('admin/gifts') && !request()->is('admin/country-requests')) $grid->disableRowSelector();
        
        $permission_name = $this->permission_name;

        if (!Admin::user()->can('*')) {
            if (!Admin::user()->can('edit-' . $permission_name) && !Admin::user()->can('update-' . $permission_name)) {
                $grid->hiddenColumns = is_array($this->hiddenColumns) ? $this->hiddenColumns : [];
            }
            if (! Admin::user()->can('delete-' . $permission_name)) {
                $grid->disableRowSelector();
            }
            if (! Admin::user()->can('create-' . $permission_name)) {
                $grid->disableCreateButton();
            }
            $grid->actions(
                function ($actions) use ($permission_name) {

                    // The roles with this permission will not able to see the delete button in actions column.
                    if (! Admin::user()->can('delete-' . $permission_name)) {
                        $actions->disableDelete();
                    }
                    if (! Admin::user()->can('edit-' . $permission_name)) {
                        $actions->disableEdit();
                    }
                    if (! Admin::user()->can('show-' . $permission_name)) {
                        $actions->disableView();
                    }
                }
            );
            if (! Admin::user()->can('edit-' . $permission_name) && ! Admin::user()->can('delete-' . $permission_name) && ! Admin::user()->can('create-' . $permission_name)) {
                $grid->disableActions();
            }
        }



        $grid->export(function ($export) use ($grid) {

            $export->filename($this->permission_name . '.csv');
            if ($this->hiddenColumns == null) {
                $export->except([]);
            } else {
                $export->except($this->hiddenColumns);
            }

            //            $export->only(['column3', 'column4' ...]);
            //
            $export->originalValue($grid->columnNames);
            //
            //            $export->column('column_5', function ($value, $original) {
            //                return $value;
            //            });
        });
    }


    public function extendShow($show)
    {
        if (!Admin::user()->can('*')) {
            $show->panel()
                ->tools(
                    function ($tools) {
                        $tools->disableEdit();
                        $tools->disableList();
                        $tools->disableDelete();
                    }
                );
        }
    }

    protected function disableFormTools(Form $form)
    {
        if (request()->is('*edit*')) {
            $form->tools(function (Form\Tools $tools) {
                $tools->disableDelete();
            });
        }
    }
}
