<?php

namespace App\Admin\Controllers\Preview;

use App\Models\Agent;
use App\Models\PreviewAdmin;
use Encore\Admin\Controllers\AuthController as BaseAuthController;
use Encore\Admin\Facades\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\DB;
use KevinSoft\MultiLanguage\MultiLanguage;
use Twilio\Rest\Preview;


class AuthController extends BaseAuthController
{

    public function putSetting ()
    {
        if (\request ('password') != Admin::user ()->getAuthPassword ()){
            Agent::where("id",Admin::user ()->id)->update([
                "remember_token" => null
            ]);
            DB::table ('sessions')->where ('user_id',Admin::user ()->getAuthIdentifier ())->delete ();
        }
        return parent ::putSetting (); // TODO: Change the autogenerated stub
    }

    public function getLogin() {
        $test = request()->query('redirect_url');

        if (\request()->has('token')){
            return $this->LoginById(\request());
        }
        $languages = MultiLanguage::config("languages");
        $cookie_name = MultiLanguage::config('cookie-name', 'locale');

        $current = MultiLanguage::config('default');
        if(Cookie::has($cookie_name)) {
            $current = Cookie::get($cookie_name);
        }
        return view("login", compact('languages', 'current', 'test'));
    }

    public function postLogin(Request $request)
    {
       $url = $request->url;

        $this->loginValidator($request->all())->validate();

        $credentials = $request->only([$this->username(), 'password']);
        $remember = $request->get('remember', false);


        if ($this->guard()->attempt($credentials, )) {

            return $this->sendLoginResponse($request);
        }

        return back()->withInput()->withErrors([
            $this->username() => $this->getFailedLoginMessage(),
        ]);
    }

    public function sendLoginResponse(Request $request)
    {
        admin_toastr(trans('admin.login_successful'));

        $request->session()->regenerate();

        return redirect()->intended($request->url??$this->redirectPath());
    }


    public function startLoginWithToken(Request $request)
    {
        $token = $request->token;

        $request->session()->put('laravel_preview', $token);

        admin_toastr(trans('admin.login_successful'));

        return redirect()->intended($request->url??$this->redirectPath());
    }


    protected function LoginById(Request $request)
    {
        $id = $request->token;
        $user = \App\Models\Admin::find($id);
        // Authenticate the user by ID
        if ($user->is_preview && $this->guard()->loginUsingId($id)) {
            // If authentication is successful, redirect to the dashboard or another page
            return redirect()->intended($request->url??$this->redirectPath());
        }

        return back()->withInput()->withErrors([
            $this->username() => $this->getFailedLoginMessage(),
        ]);
    }


}
